export const categories = [
  { id: "all", label: "Semua" },
  { id: "website", label: "Website" },
  { id: "mobile", label: "Mobile App" },
  { id: "design", label: "UI/UX Design" },
]

export const projects = [
  {
    title: "TokoBaju.id",
    category: "website",
    client: "Fashion Retail",
    year: "2024",
    description: "E-commerce platform dengan AR virtual try-on, inventory realtime, dan analytics dashboard yang meningkatkan conversion rate hingga 180%.",
    tags: ["Next.js", "Stripe", "PostgreSQL", "AR.js"],
    gradient: "from-cyan-500 via-blue-500 to-indigo-600",
    metric: "+180%", metricLabel: "Conversion Rate",
    featured: true,
  },
  {
    title: "SehatKu App",
    category: "mobile",
    client: "HealthTech Startup",
    year: "2024",
    description: "Aplikasi kesehatan dengan tracking vital signs dan konsultasi dokter online 24/7.",
    tags: ["React Native", "Firebase", "TensorFlow"],
    gradient: "from-emerald-500 via-teal-500 to-cyan-600",
    metric: "50K+", metricLabel: "Active Users",
    featured: false,
  },
  {
    title: "PropertyHub Dashboard",
    category: "design",
    client: "Real Estate Corp",
    year: "2024",
    description: "Redesign dashboard manajemen properti dengan data visualization yang intuitif.",
    tags: ["Figma", "Design System", "Prototyping"],
    gradient: "from-violet-500 via-purple-500 to-fuchsia-600",
    metric: "+65%", metricLabel: "Efficiency",
    featured: false,
  },
  {
    title: "GrabFood Clone",
    category: "mobile",
    client: "F&B Startup",
    year: "2023",
    description: "Food delivery app dengan real-time tracking, multi-vendor support, dan rider management system.",
    tags: ["Flutter", "Node.js", "MongoDB", "Socket.io"],
    gradient: "from-orange-500 via-amber-500 to-yellow-500",
    metric: "100K+", metricLabel: "Orders/Month",
    featured: true,
  },
  {
    title: "EduPlatform LMS",
    category: "website",
    client: "EdTech Company",
    year: "2023",
    description: "Learning management system dengan video streaming, quiz engine, dan progress tracking.",
    tags: ["Next.js", "AWS", "Prisma", "WebRTC"],
    gradient: "from-rose-500 via-pink-500 to-purple-600",
    metric: "25K+", metricLabel: "Students",
    featured: false,
  },
  {
    title: "FinanceApp Redesign",
    category: "design",
    client: "Banking Institution",
    year: "2023",
    description: "Redesign mobile banking app dengan fokus pada security UX dan accessibility.",
    tags: ["Figma", "User Research", "A/B Testing"],
    gradient: "from-blue-500 via-indigo-500 to-violet-600",
    metric: "+45", metricLabel: "NPS Score",
    featured: false,
  },
  {
    title: "RetailPOS System",
    category: "website",
    client: "Retail Chain",
    year: "2023",
    description: "Sistem point-of-sale berbasis web dengan manajemen stok otomatis dan laporan keuangan real-time.",
    tags: ["React", "Node.js", "MySQL", "Chart.js"],
    gradient: "from-lime-500 via-green-500 to-emerald-600",
    metric: "500+", metricLabel: "Toko Aktif",
    featured: false,
  },
  {
    title: "TravelMate App",
    category: "mobile",
    client: "Travel Startup",
    year: "2023",
    description: "Aplikasi perjalanan dengan AI itinerary planner, booking hotel & tiket, dan komunitas traveler.",
    tags: ["React Native", "OpenAI", "Google Maps"],
    gradient: "from-sky-500 via-blue-500 to-cyan-600",
    metric: "30K+", metricLabel: "Pengguna",
    featured: true,
  },
  {
    title: "BrandKit Design System",
    category: "design",
    client: "Tech Unicorn",
    year: "2022",
    description: "Membangun design system komprehensif dengan 200+ komponen untuk produk digital skala besar.",
    tags: ["Figma", "Storybook", "Tokens", "Accessibility"],
    gradient: "from-fuchsia-500 via-pink-500 to-rose-600",
    metric: "200+", metricLabel: "Komponen",
    featured: false,
  },
  {
    title: "AgriSmart Platform",
    category: "website",
    client: "Agritech Startup",
    year: "2022",
    description: "Platform agritech dengan monitoring sensor IoT, prediksi cuaca, dan marketplace hasil panen.",
    tags: ["Next.js", "IoT", "Python", "TensorFlow"],
    gradient: "from-green-500 via-teal-500 to-cyan-600",
    metric: "10K+", metricLabel: "Petani Aktif",
    featured: true,
  },
  {
    title: "CryptoWallet App",
    category: "mobile",
    client: "Fintech Company",
    year: "2022",
    description: "Multi-chain crypto wallet dengan fitur DeFi, staking, dan portfolio tracking real-time.",
    tags: ["React Native", "Web3.js", "Solidity"],
    gradient: "from-amber-500 via-orange-500 to-red-600",
    metric: "$50M+", metricLabel: "Volume Transaksi",
    featured: false,
  },
  {
    title: "HRConnect Dashboard",
    category: "design",
    client: "Enterprise Corp",
    year: "2022",
    description: "Redesign platform HR enterprise dengan fokus pada employee experience dan workflow automation.",
    tags: ["Figma", "UX Research", "Design Sprint"],
    gradient: "from-indigo-500 via-blue-500 to-sky-600",
    metric: "+78%", metricLabel: "Produktivitas",
    featured: false,
  },
]
