export const categories = [
  { id: "all", label: "Semua" },
  { id: "website", label: "Website" },
  { id: "mobile", label: "Mobile App" },
  { id: "design", label: "UI/UX Design" },
  { id: "desktop", label: "Aplikasi Desktop" },
];

export const projects = [
  {
    title: "Rental PS",
    category: "website",
    client: "Gaming Rental Service",
    year: "2024",
    description:
      "Website rental PlayStation dengan booking online, stok real-time, dan sistem pembayaran digital yang mudah digunakan.",
    tags: ["Next.js", "Stripe", "PostgreSQL", "TailwindCSS"],
    gradient: "from-blue-500 via-indigo-500 to-purple-600",
    metric: "200+",
    metricLabel: "Sewaan/Bulan",
    featured: true,
    image: "/portofolio-1.png",
    liveUrl: "https://rental-ps-gray.vercel.app/",
  },
  {
    title: "Ayam Geprek",
    category: "website",
    client: "F&B Business",
    year: "2024",
    description:
      "Website usaha ayam geprek dengan menu online, sistem pesan-antar, dan manajemen pesanan yang efisien.",
    tags: ["React", "Node.js", "MongoDB", "Google Maps"],
    gradient: "from-orange-500 via-red-500 to-yellow-500",
    metric: "150+",
    metricLabel: "Pesanan/Hari",
    featured: true,
    image: "/portofolio-2.png",
    liveUrl: "https://ayam-geprek-theta.vercel.app/",
  },
  {
    title: "Babershop",
    category: "website",
    client: "Grooming Service",
    year: "2024",
    description:
      "Website babershop dengan booking online, galeri potongan, dan sistem reminder untuk pelanggan setia.",
    tags: ["Next.js", "Firebase", "TailwindCSS", "Calendar API"],
    gradient: "from-gray-500 via-slate-500 to-zinc-600",
    metric: "80+",
    metricLabel: "Pelanggan/Minggu",
    featured: true,
    image: "/portofolio-3.png",
    liveUrl: "https://babershop-eight.vercel.app/",
  },
  {
    title: "PT Seiiki",
    category: "website",
    client: "Educational Institution",
    year: "2024",
    description:
      "Website resmi untuk PT Seiiki dengan sistem informasi akademik, portal siswa, dan manajemen kegiatan sekolah.",
    tags: ["Next.js", "PostgreSQL", "TailwindCSS", "Prisma"],
    gradient: "from-blue-500 via-cyan-500 to-teal-600",
    metric: "1000+",
    metricLabel: "Siswa Aktif",
    featured: true,
    image: "/portofolio-4.png",
    liveUrl: "https://seyiki.com/",
  },
  {
    title: "EPIC 2026",
    category: "website",
    client: "International Conference",
    year: "2024",
    description:
      "Website resmi untuk The 5th Engineering Physics International Conference dengan sistem registrasi, jadwal sesi, dan informasi pembicara.",
    tags: ["Next.js", "TypeScript", "TailwindCSS", "PostgreSQL"],
    gradient: "from-purple-500 via-violet-500 to-indigo-600",
    metric: "500+",
    metricLabel: "Peserta",
    featured: true,
    image: "/portofolio-5.png",
    liveUrl: "https://epic.itera.ac.id/",
  },
  {
    title: "Survei Seiiki",
    category: "website",
    client: "Educational Institution",
    year: "2024",
    description:
      "Website sistem survei untuk PT Seiiki dengan form dinamis, analisis data real-time, dan laporan otomatis.",
    tags: ["Next.js", "Node.js", "MongoDB", "Chart.js"],
    gradient: "from-emerald-500 via-teal-500 to-cyan-600",
    metric: "2000+",
    metricLabel: "Responden",
    featured: true,
    image: "/portofolio-6.png",
    liveUrl: "https://survei.seyiki.com/",
  },
  {
    title: "Docs Seiiki",
    category: "website",
    client: "Educational Institution",
    year: "2024",
    description:
      "Website penyimpanan dokumen untuk PT Seiiki dengan sistem upload, pengaturan akses, dan organisasi file yang efisien.",
    tags: ["Next.js", "AWS S3", "PostgreSQL", "TailwindCSS"],
    gradient: "from-amber-500 via-orange-500 to-red-500",
    metric: "5000+",
    metricLabel: "Dokumen",
    featured: true,
    image: "/portofolio-7.png",
    liveUrl: "https://docs.seyiki.com/",
  },
  {
    title: "KM Itera",
    category: "website",
    client: "Student Organization",
    year: "2024",
    description:
      "Website keluarga mahasiswa ITERA dengan portal informasi kegiatan, forum diskusi, dan manajemen anggota.",
    tags: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS"],
    gradient: "from-blue-600 via-indigo-500 to-purple-600",
    metric: "2000+",
    metricLabel: "Anggota Aktif",
    featured: true,
    image: "/portofolio-8.png",
    liveUrl: "https://www.km-itera.com/",
  },
  {
    title: "Candidate College",
    category: "website",
    client: "Educational Platform",
    year: "2024",
    description:
      "Platform edukasi untuk persiapan kuliah dengan sistem pembelajaran, tryout online, dan analisis hasil.",
    tags: ["Next.js", "Node.js", "MongoDB", "Chart.js"],
    gradient: "from-green-500 via-emerald-500 to-teal-600",
    metric: "10K+",
    metricLabel: "Siswa",
    featured: true,
    image: "/portofolio-9.png",
    liveUrl: "https://candidate-college.vercel.app/",
  },
  {
    title: "Website Penerimaan Mahasiswa Baru ITERA 2024",
    category: "website",
    client: "Penerimaan Mahasiswa Baru ITERA",
    year: "2024",
    description: "Website penerimaan mahasiswa baru ITERA tahun 2024.",
    tags: ["Next.js", "TailwindCSS"],
    gradient: "from-blue-500 via-cyan-500 to-teal-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-10.png",
    liveUrl: "https://pplikitera.com",
  },
  {
    title: "Website Penerimaan Mahasiswa Baru ITERA 2025",
    category: "website",
    client: "Penerimaan Mahasiswa Baru ITERA",
    year: "2025",
    description: "Website penerimaan mahasiswa baru ITERA tahun 2025.",
    tags: ["Next.js", "TailwindCSS"],
    gradient: "from-blue-600 via-indigo-500 to-purple-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-11.png",
    liveUrl: "https://pplkitera.com",
  },
  {
    title: "LHPP Generator",
    category: "website",
    client: "PT Seiiki",
    year: "2024",
    description:
      "Website LHPP generator untuk PT Seiiki yang menghasilkan laporan otomatis.",
    tags: ["Next.js", "Node.js"],
    gradient: "from-emerald-500 via-teal-500 to-cyan-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-12.png",
    liveUrl: "https://lhpp.seyiki.com/",
  },
  {
    title: "IoT Control - Monitoring & Kontrol Lampu & AC Kampus",
    category: "website",
    client: "Universitas Lampung",
    year: "2024",
    description:
      "Platform IoT untuk monitoring dan kontrol lampu serta AC di kampus.",
    tags: ["IoT", "Node.js", "MQTT"],
    gradient: "from-sky-500 via-blue-500 to-cyan-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-13.png",
    liveUrl: "https://iot.seyiki.com/",
  },
  {
    title: "SaaS Business Analysis - PT Meita Gudang Distribusi",
    category: "website",
    client: "PT Meita",
    year: "2024",
    description:
      "SaaS untuk business analysis dan manajemen distribusi gudang.",
    tags: ["SaaS", "Next.js", "PostgreSQL"],
    gradient: "from-indigo-500 via-purple-500 to-fuchsia-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-14.png",
    liveUrl: "https://gudangdistribusi.com/home",
  },
  {
    title: "Sistem Pencatatan SPP SMA 13 PGRI",
    category: "website",
    client: "SMA 13 PGRI",
    year: "2024",
    description:
      "Website internal pencatatan SPP untuk SMA 13 PGRI (running di localhost).",
    tags: ["PHP", "MySQL"],
    gradient: "from-yellow-500 via-amber-500 to-orange-500",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-15.png",
  },
  {
    title: "Web Caffe POS (Multi-role)",
    category: "website",
    client: "Post Kafe",
    year: "2024",
    description:
      "Sistem POS kafe dengan 6 role: owner, manager, gudang, kasir, kafe, pelayan.",
    tags: ["Next.js", "Role-based Auth"],
    gradient: "from-cyan-500 via-blue-500 to-indigo-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-16.png",
    liveUrl: "https://web-caffe-pos-cabang-pos-kafe.vercel.app/login",
  },
  {
    title: "MBG POS (Multi-role)",
    category: "website",
    client: "MBG",
    year: "2024",
    description:
      "Sistem POS MBG dengan role admin, manajer, staff, gudang, yayasan, dan driver.",
    tags: ["Node.js", "Express", "Role-based Auth"],
    gradient: "from-rose-500 via-pink-500 to-purple-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-17.png",
    liveUrl: "https://mbg-api-server.vercel.app/login",
  },
  {
    title: "Pemira KM ITERA 2025-2026",
    category: "website",
    client: "KM ITERA",
    year: "2025",
    description:
      "Website pemilihan presiden mahasiswa ITERA untuk periode 2025-2026.",
    tags: ["Next.js", "Voting"],
    gradient: "from-green-500 via-emerald-500 to-teal-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-18.png",
    liveUrl: "http://pemira-km-itera.my.id/",
  },
  {
    title: "Connect Printing - Chek Kupon",
    category: "website",
    client: "Connect Printing",
    year: "2024",
    description:
      "Website cek kupon untuk usaha printing di Surabaya (Connect Printing).",
    tags: ["Next.js", "Node.js"],
    gradient: "from-gray-500 via-slate-500 to-zinc-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-19.png",
  },
  {
    title: "Rental Alat Pesta",
    category: "website",
    client: "Rental Alat Pesta",
    year: "2024",
    description:
      "Website rental alat pesta dengan katalog online dan sistem pemesanan.",
    tags: ["Next.js", "Stripe"],
    gradient: "from-purple-500 via-pink-500 to-rose-500",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-23.png",
    liveUrl: "https://rental-alat-pesta.vercel.app/",
  },
  {
    title: "Weekly Report — Candidate College Jakarta",
    category: "website",
    client: "Candidate College Jakarta",
    year: "2024",
    description:
      "Website internal weekly report untuk usaha Candidate College di Jakarta.",
    tags: ["Internal", "Next.js"],
    gradient: "from-indigo-500 via-blue-500 to-sky-500",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-24.png",
  },
  {
    title: "Desktop Bot — Auto Login & Auto Claim",
    category: "desktop",
    client: "Internal Tool",
    year: "2024",
    description:
      "Aplikasi desktop untuk otomatisasi login, auto-claim hadiah, dan tugas rutin lainnya (internal automation tool).",
    tags: ["Electron", "Node.js", "Automation"],
    gradient: "from-gray-700 via-gray-600 to-gray-500",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-20.png",
    liveUrl: "",
  },
  {
    title: "Pengumuman Kelulusan SMA Negeri 1 Padang Gelugur",
    category: "website",
    client: "SMA Negeri 1 Padang Gelugur",
    year: "2024",
    description:
      "Website pengumuman kelulusan untuk SMA Negeri 1 Padang Gelugur.",
    tags: ["Next.js", "TailwindCSS"],
    gradient: "from-blue-500 via-cyan-500 to-teal-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-21.png",
    liveUrl: "https://pengunguman-kelulusan-sma.vercel.app/",
  },
  {
    title: "AgroMonitoring - IoT Suhu & Cahaya",
    category: "website",
    client: "Agro Monitoring",
    year: "2024",
    description:
      "Website IoT untuk monitoring suhu dan cahaya di sekitar tanaman.",
    tags: ["IoT", "Node.js", "React"],
    gradient: "from-green-500 via-emerald-500 to-teal-600",
    metric: "—",
    metricLabel: "",
    featured: false,
    image: "/portofolio-25.png",
    liveUrl: "https://agromonitoring.onrender.com/",
  },
  {
    title: "PT ESKM — Company Profile",
    category: "website",
    client: "PT Sumber Energi Kehidupan Manusia",
    year: "2025",
    description:
      "Website company profile untuk PT ESKM, perusahaan energi terbarukan. Menampilkan layanan upgrade daya listrik PLN dan solusi kelistrikan modern untuk rumah tangga dan komersial.",
    tags: ["Next.js", "TailwindCSS", "TypeScript"],
    gradient: "from-red-500 via-orange-500 to-yellow-500",
    metric: "100%",
    metricLabel: "Uptime",
    featured: true,
    image: "/portofolio-26.png",
    liveUrl: "https://eskm.com",
  },
  {
    title: "Portfolio Mahasiswa UNSW Sydney",
    category: "website",
    client: "Zaki Fathi Fahrizal",
    year: "2025",
    description:
      "Website portofolio personal untuk mahasiswa Mechanical Engineering di UNSW Sydney, menampilkan proyek CFD, FEA, dan desain robot bawah laut.",
    tags: ["React", "TailwindCSS", "Vercel"],
    gradient: "from-blue-500 via-indigo-500 to-violet-600",
    metric: "3.64",
    metricLabel: "GPA / 4.00",
    featured: true,
    image: "/portofolio-27.png",
    liveUrl: "https://zaki-fathi-fahrizal.vercel.app/",
  },
  {
    title: "Travel Agency — Jelajahi Dunia",
    category: "website",
    client: "Travel Agency",
    year: "2025",
    description:
      "Website travel agency dengan fitur pencarian penerbangan, pemesanan hotel, dan paket wisata lengkap. Tersedia dalam tampilan bilingual.",
    tags: ["Next.js", "TailwindCSS", "API Integrasi"],
    gradient: "from-amber-500 via-yellow-400 to-lime-500",
    metric: "100+",
    metricLabel: "Destinasi",
    featured: true,
    image: "/portofolio-28.png",
    liveUrl: "https://travel-seven-sigma.vercel.app/",
  },
  {
    title: "Si Poljar — Monitoring Kualitas Udara",
    category: "website",
    client: "Monitoring Kualitas Udara Sekolah",
    year: "2025",
    description:
      "Dashboard IoT real-time untuk memantau kualitas udara di lingkungan sekolah. Menampilkan indeks kualitas udara, suhu, CO₂, PM2.5, dan rekomendasi ventilasi.",
    tags: ["React", "IoT", "Recharts", "WebSocket"],
    gradient: "from-sky-500 via-blue-500 to-cyan-600",
    metric: "6",
    metricLabel: "Sensor Live",
    featured: true,
    image: "/portofolio-29.png",
    liveUrl: "https://monitoring-kualitas-udara.onrender.com/",
  },
  {
    title: "PEMIRA HIMATEKIA-ITERA 2025",
    category: "website",
    client: "Himpunan Mahasiswa Teknik Kimia ITERA",
    year: "2025",
    description:
      "Website pemilihan ketua himpunan mahasiswa teknik kimia ITERA dengan sistem voting aman, verifikasi berlapis, dan hasil real-time yang transparan.",
    tags: ["Next.js", "PostgreSQL", "Auth", "TailwindCSS"],
    gradient: "from-violet-500 via-purple-500 to-indigo-600",
    metric: "Real-time",
    metricLabel: "Hasil Voting",
    featured: false,
    image: "/portofolio-33.png",
    liveUrl: "http://pemira-himatekia-itera.my.id/",
  },
  {
    title: "KomikKuy — Baca Komik Online",
    category: "website",
    client: "KomikKuy",
    year: "2025",
    description:
      "Platform baca komik online dengan koleksi lengkap, sistem chapter, dan tampilan yang nyaman untuk pembaca.",
    tags: ["Next.js", "MongoDB", "TailwindCSS"],
    gradient: "from-pink-500 via-rose-500 to-red-500",
    metric: "1000+",
    metricLabel: "Komik",
    featured: false,
    image: "/portofolio-34.png",
    liveUrl: "https://komikkuy.my.id/",
  },
  {
    title: "Undangan Pernikahan Digital",
    category: "website",
    client: "Lavender Bloom Invites",
    year: "2025",
    description:
      "Website undangan pernikahan digital elegan dengan tema lavender, countdown hari-H, galeri foto, RSVP online, dan petunjuk lokasi.",
    tags: ["Next.js", "TailwindCSS", "Animation"],
    gradient: "from-purple-400 via-lavender-400 to-pink-400",
    metric: "100%",
    metricLabel: "Responsif",
    featured: false,
    image: "/portofolio-35.png",
    liveUrl: "https://lavender-bloom-invites.vercel.app/",
  },
  {
    title: "Smart Center Indonesia — Bimbel",
    category: "website",
    client: "Smart Center Indonesia, Pekanbaru",
    year: "2025",
    description:
      "Website bimbingan belajar Smart Center Indonesia di Pekanbaru. Menampilkan program unggulan, jadwal kelas, pendaftaran online, dan testimoni siswa.",
    tags: ["Next.js", "TailwindCSS", "CMS"],
    gradient: "from-blue-600 via-cyan-500 to-teal-500",
    metric: "500+",
    metricLabel: "Siswa",
    featured: true,
    image: "/portofolio-31.png",
    liveUrl: "https://smartcenterindonesia.com/",
  },
  {
    title: "E-Wallet Nick Lookup",
    category: "website",
    client: "E-Wallet Nick Lookup",
    year: "2025",
    description:
      "Website untuk mengecek nama pemilik akun e-wallet berdasarkan nomor rekening. Mendukung berbagai provider e-wallet populer di Indonesia.",
    tags: ["React", "Node.js", "API"],
    gradient: "from-emerald-500 via-green-500 to-teal-500",
    metric: "Multi",
    metricLabel: "Provider",
    featured: false,
    image: "/portofolio-30.png",
    liveUrl: "https://ewalletnicklookupv2-1.onrender.com/",
  },
  {
    title: "Jastip Anggung Jaya — Manokwari",
    category: "website",
    client: "Jastip Anggung Jaya, Papua Barat",
    year: "2025",
    description:
      "Website jasa titip (jastip) untuk usaha Anggung Jaya di Manokwari, Papua Barat. Memudahkan pelanggan memesan barang dengan sistem titip yang praktis.",
    tags: ["Next.js", "TailwindCSS", "WhatsApp API"],
    gradient: "from-orange-500 via-amber-500 to-yellow-400",
    metric: "Papua",
    metricLabel: "Barat",
    featured: false,
    image: "/portofolio-32.png",
    liveUrl: "https://38-103-170-185.sslip.io/",
  },
];
